import type { DimensionKey } from './vitality';

export const LABELS = {
  en: {
    section: "Activity",
    debugShow: "Show debug",
    debugHide: "Hide debug",
    groupCode: "Code",
    groupCommunity: "Community",
    info: "Info",
    contributors: "Contributors",
    commitsAll: "Commits, all time",
    mergesAll: "Pull requests, all time",
    commitsWindow: (d: number) => `Commits, last ${d} days`,
    mergesWindow: (d: number) => `Pull requests, last ${d} days`,
    stars: "Stars",
    forks: "Forks",
    issuesOpen: "Open issues",
    issuesClosed: "Closed issues",
    tags: "Tags",
    oldestCommit: "First commit",
    dim: {
      contributors: "Contributors",
      history: "Project history",
      activity: "Current activity",
      stars: "Stars",
      issues: "Issues",
      forks: "Forks",
    } as Record<DimensionKey, string>,
    colDimension: "Dimension",
    colRaw: "Raw",
    colNorm: "Level",
    colWeight: "Weight",
    colContribution: "Points",
    config: "Configure index",
    weights: "Weights",
    commits: "commits",
    merges: "pull requests",
    issueMode: "Issues mode",
    modeRatio: "Open/closed ratio",
    modeOpen: "Open issues only",
    xmaxMode: "Reference max",
    xmaxMax: "Maximum",
    xmaxP95: "95th percentile",
    weightSum: "Sum",
    reset: "Reset to defaults",
    resetGlobal: "Reset to global",
    overrideActive: "Custom weights for this software",
    stepUp: "Increase",
    stepDown: "Decrease",
    settingsIntro: "These weights apply to the whole catalog and seed the widget on each software page.",
    na: "n/d",
    unavailable: "unavailable",
    excluded: "excluded (no data)",
    scoreUnavailable: "Index not computed: some metrics could not be collected",
    scoreScope: (covered: number, total: number) => `Based on ${covered} of ${total} metrics`,
    rowDisabled: "disabled",
    rowUnknown: "unknown",
    capDisabled: "Capped at 89: a forge feature is disabled",
    capUnknown: "Capped at 79: some metrics are unknown",
  },
  it: {
    section: "Attività",
    debugShow: "Mostra debug",
    debugHide: "Nascondi debug",
    groupCode: "Codice",
    groupCommunity: "Community",
    info: "Info",
    contributors: "Contributori",
    commitsAll: "Commit, totali",
    mergesAll: "Pull request, totali",
    commitsWindow: (d: number) => `Commit, ultimi ${d} giorni`,
    mergesWindow: (d: number) => `Pull request, ultimi ${d} giorni`,
    stars: "Stelle",
    forks: "Fork",
    issuesOpen: "Issue aperte",
    issuesClosed: "Issue chiuse",
    tags: "Tag",
    oldestCommit: "Primo commit",
    dim: {
      contributors: "Contributori",
      history: "Storia del progetto",
      activity: "Attività recente",
      stars: "Stelle",
      issues: "Issue",
      forks: "Fork",
    } as Record<DimensionKey, string>,
    colDimension: "Dimensione",
    colRaw: "Grezzo",
    colNorm: "Livello",
    colWeight: "Peso",
    colContribution: "Punti",
    config: "Configura indice",
    weights: "Pesi",
    commits: "commit",
    merges: "pull request",
    issueMode: "Modalità issue",
    modeRatio: "Rapporto aperte/chiuse",
    modeOpen: "Solo issue aperte",
    xmaxMode: "Massimo di riferimento",
    xmaxMax: "Massimo",
    xmaxP95: "95° percentile",
    weightSum: "Somma",
    reset: "Ripristina default",
    resetGlobal: "Ripristina globale",
    overrideActive: "Pesi personalizzati per questo software",
    stepUp: "Aumenta",
    stepDown: "Diminuisci",
    settingsIntro: "Questi pesi valgono per tutto il catalogo e fanno da default nel widget di ogni software.",
    na: "n/d",
    unavailable: "non disponibile",
    excluded: "esclusa (dati assenti)",
    scoreUnavailable: "Indice non calcolato: alcuni dati non sono stati raccolti",
    scoreScope: (covered: number, total: number) => `Basato su ${covered} metriche su ${total}`,
    rowDisabled: "disattivato",
    rowUnknown: "sconosciuto",
    capDisabled: "Limitato a 89: una funzione della forge è disattivata",
    capUnknown: "Limitato a 79: alcune metriche sono sconosciute",
  },
};
