import type { DimensionKey } from './vitality';

export const LABELS = {
  en: {
    section: "Activity",
    scoreLabel: "Activity score",
    debugShow: "Show points distribution",
    debugHide: "Hide points distribution",
    groupCode: "Code",
    groupCommunity: "Community",
    info: "Info",
    contributors: "Contributors",
    commitsAll: "Commits, all time",
    mergesAll: "Pull requests, all time",
    commitsWindow: (d: number) => `Commits, last ${d} days`,
    mergesWindow: (d: number) => `Pull requests, last ${d} days`,
    stars: "Stars",
    forks: "Forks",
    issuesOpen: "Open issues",
    issuesClosed: "Closed issues",
    oldestCommit: "First commit",
    dim: {
      contributors: "Contributors",
      history: "Project history",
      activity: "Current activity",
      stars: "Stars",
      issues: "Issues",
      forks: "Forks",
    } as Record<DimensionKey, string>,
    colDimension: "Dimension",
    colRaw: "Raw",
    colNorm: "Level",
    colWeight: "Weight",
    colContribution: "Points",
    config: "Configure index",
    weights: "Weights",
    globalWeights: "Activity weights",
    showWeights: "Weights",
    hideWeights: "Weights",
    freePoints: "{points}% left to assign",
    freePointsOver: "{points}% over 100",
    stateFailed: "error",
    stateFailedTitle: "data fetch failed",
    stateUnknown: "...",
    stateUnknownTitle: "we have not collected this data yet",
    stateDisabled: "n/a",
    overAllocatedTitle: "weights exceed 100, free the extra points first",
    commits: "commits",
    merges: "pull requests",
    issueMode: "Issues mode",
    modeRatio: "Open/closed ratio",
    modeOpen: "Overall issues",
    xmaxMode: "Reference max",
    xmaxMax: "Maximum",
    xmaxP95: "95th percentile",
    weightSum: "Sum",
    reset: "Reset to defaults",
    resetGlobal: "Reset to global values",
    resetConfirmation: "Restore the default weights and index settings?",
    resetGlobalConfirmation: "Discard this software's custom weights and restore the global settings?",
    overrideActive: "Custom weights for this software",
    popoverClose: "Close",
    popoverConfirm: "Done",
    stepUp: "Increase",
    stepDown: "Decrease",
    settingsIntro: "These weights apply to the whole catalog and seed the widget on each software page.",
    activityDebug: "Show activity score debug details",
    activityDebugHelp: "Weight breakdown, colored bar and custom weights, per software and global.",
    openCodeBadges: "openCode.de badges",
    openCodeBadgesHelp: "Show badge details and their radar on software pages.",
    na: "n/d",
    unavailable: "unavailable",
    excluded: "excluded (no data)",
    scorePending: "Activity score on its way: we have not collected all of its data yet",
    scorePendingTitle: "Activity score on its way: we have not collected all of its data yet",
    rowDisabled: "disabled",
    rowUnknown: "not collected yet",
    capDisabled: "Capped at 89: a forge feature is disabled",
  },
  it: {
    section: "Attività",
    scoreLabel: "Punteggio attività",
    debugShow: "Mostra distribuzione dei punti",
    debugHide: "Nascondi distribuzione dei punti",
    groupCode: "Codice",
    groupCommunity: "Community",
    info: "Info",
    contributors: "Contributori",
    commitsAll: "Commit, totali",
    mergesAll: "Pull request, totali",
    commitsWindow: (d: number) => `Commit, ultimi ${d} giorni`,
    mergesWindow: (d: number) => `Pull request, ultimi ${d} giorni`,
    stars: "Stelle",
    forks: "Fork",
    issuesOpen: "Issue aperte",
    issuesClosed: "Issue chiuse",
    oldestCommit: "Primo commit",
    dim: {
      contributors: "Contributori",
      history: "Storia del progetto",
      activity: "Attività recente",
      stars: "Stelle",
      issues: "Issue",
      forks: "Fork",
    } as Record<DimensionKey, string>,
    colDimension: "Dimensione",
    colRaw: "Grezzo",
    colNorm: "Livello",
    colWeight: "Peso",
    colContribution: "Punti",
    config: "Configura indice",
    weights: "Pesi",
    globalWeights: "Pesi attività",
    showWeights: "Pesi",
    hideWeights: "Pesi",
    freePoints: "{points}% da assegnare",
    freePointsOver: "{points}% oltre 100",
    stateFailed: "errore",
    stateFailedTitle: "recupero dati fallito",
    stateUnknown: "...",
    stateUnknownTitle: "non abbiamo ancora raccolto questo dato",
    stateDisabled: "n/d",
    overAllocatedTitle: "i pesi superano 100, libera prima i punti in eccesso",
    commits: "commit",
    merges: "pull request",
    issueMode: "Modalità issue",
    modeRatio: "Rapporto aperte/chiuse",
    modeOpen: "Issue complessive",
    xmaxMode: "Massimo di riferimento",
    xmaxMax: "Massimo",
    xmaxP95: "95° percentile",
    weightSum: "Somma",
    reset: "Ripristina default",
    resetGlobal: "Ripristina valori globali",
    resetConfirmation: "Ripristinare i pesi e le impostazioni dell'indice ai valori predefiniti?",
    resetGlobalConfirmation: "Eliminare i pesi personalizzati di questo software e ripristinare le impostazioni globali?",
    overrideActive: "Pesi personalizzati per questo software",
    popoverClose: "Chiudi",
    popoverConfirm: "Done",
    stepUp: "Aumenta",
    stepDown: "Diminuisci",
    settingsIntro: "Questi pesi valgono per tutto il catalogo e fanno da default nel widget di ogni software.",
    activityDebug: "Mostra i dettagli di debug del punteggio attività",
    activityDebugHelp: "Distribuzione dei pesi, barra colorata e pesi personalizzati, per software e globali.",
    openCodeBadges: "Badge openCode.de",
    openCodeBadgesHelp: "Mostra i dettagli dei badge e il loro spider chart nelle pagine software.",
    na: "n/d",
    unavailable: "non disponibile",
    excluded: "esclusa (dati assenti)",
    scorePending: "Punteggio attività in arrivo: non abbiamo ancora raccolto tutti i dati",
    scorePendingTitle: "Punteggio attività in arrivo: non abbiamo ancora raccolto tutti i dati",
    rowDisabled: "disattivato",
    rowUnknown: "non ancora raccolto",
    capDisabled: "Limitato a 89: una funzione della forge è disattivata",
  },
};
